name: sima_rqa
version: 1.1.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  flutterflow_ui: ^0.2.0+1
  dio: ^5.3.0
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.0.1
  intl: ^0.18.1
  file_picker: ^5.5.0
  path_provider: ^2.0.2
  printing: ^5.12.0
  qr_flutter: ^4.1.0
  pretty_qr_code: ^3.3.0
  skeletonizer: ^1.0.1
  qrscan: ^0.3.3
  loading_animation_widget: ^1.2.1
  permission_handler: ^11.0.1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/